[package]
name = "sensor-link-console"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
sensor-link-protocol = { workspace = true, features = ["use-std"] }
chrono.workspace = true
heapless.workspace = true
rumqttc.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
clap = { version = "4.5", features = ["derive", "env"] }
log = "0.4"
simplelog = "0.12"
